version: '3.8'

services:
  AAPL:
    build: .
    container_name: AAPL
    environment:
      - TICKER=AAPL
      - FIREBASE_CONFIG={"placeholder": "config_AAPL"}

  GOOG:
    build: .
    container_name: META
    environment:
      - TICKER=META
      - FIREBASE_CONFIG={"placeholder": "config_META"}

  AMZN:
    build: .
    container_name: AMZN
    environment:
      - TICKER=AMZN
      - FIREBASE_CONFIG={"placeholder": "config_AMZN"}
