services:
  aapl:
    build: .
    container_name: aapl
    environment:
      - TICKER=AAPL
      - FIREBASE_CONFIG=

  meta:
    build: .
    container_name: meta
    environment:
      - TICKER=META
      - FIREBASE_CONFIG=

  amzn:
    build: .
    container_name: amzn
    environment:
      - TICKER=AMZN
      - FIREBASE_CONFIG=
