version: '3.8'

services:
  # Redis Service
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Trading Bot Services
  aapl-bot:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: aapl-bot
    command: AAPL
    volumes:
      - ./configs/adminsdk.json:/app/adminsdk.json:ro
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  meta-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: meta-bot
    command: META
    volumes:
      - ./configs/adminsdk.json:/app/adminsdk.json:ro
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  amzn-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: amzn-bot
    command: AMZN
    volumes:
      - ./configs/adminsdk.json:/app/adminsdk.json:ro
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  msft-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: MSFT-bot
    command: MSFT
    volumes:
      - ./configs/adminsdk.json:/app/adminsdk.json:ro
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  redis-data: